### ISSUE TITLE
should we have a Heap typeclass?

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats-collections#176]
I think we can have a `IsHeap[F[_]]` typeclass. There are many heap implementations, and we can convert the current tests into a HeapLaws to test different implementations.

something like:
```scala
trait IsHeap[F[_]] extends UnorderedFoldable[F] {
  def add[A](fa: F[A], a: A)(implicit ord: Order[A]): F[A]
  def remove[A](fa: F[A])(implicit ord: Order[A]): F[A]
  // this could be a method on UnorderedFoldable, but it was incorrectly placed on Foldable in cats
  def minimumOption[A](fa: F[A]): Option[A]
  def toList[A](fa: F[A])(implicit ord: Order[A]): List[A]
  def foldLeft[A, B](fa: F[A], init: B)(fn: (B, A) => B)(implicit ord: Order[A]): B
}
```

**Comment by larsrh** [comment]
I'm not entirely convinced that this class should be called `IsHeap`. It could apply to all collection types that impose some `Order`. Unfortunately `OrderedFoldable` would be a bad name because it means something different than the opposite of `UnorderedFoldable`. Maybe `OrderedCollection`?

The `remove` method should be renamed to `removeMin`.

**Comment by larsrh** [comment]
Fair enough. Possibly `PartiallyOrderedSet`, maybe.
